### ISSUE TITLE
light_types.py doesn't include LCA009

### ISSUE THREAD

**Issue by ohmantics** [diyhue/diyHue#1038]
### Feature does not already exist?

I searched and did not find an existing feature request

### Summarize feature

LCA009 is 100W equivalent. Things seem to work with LCA005 selected, but it's probably best to fill in all the Philips bulbs anyway.

**Comment by mariusmotea** [comment]
Hi,

It is complicated to have all the Philips bulbs because new lights values are added from time to time and without to have all these bulbs you need to do detective work in order to find these values (or guess them).

For this reason we ended by keeping one modelid per light type (strip, RGB, CCT, dimmable, plug, etc) and also most common ones to have biggest chances to find some api output on internet for it.
