### ISSUE TITLE
Save Power, when using diyhue with Powerbank

### ISSUE THREAD

**Issue by AlexKusnezov** [diyhue/diyHue#139]
**Is your feature request related to a problem? Please describe.**
Hey guys, I use nodemcu2 with 72led strip ws2813 and have it connected to a power bank which has 20000mah. Noramlly it lasts about 4 days of regular usage, mostly on at evening for a couple of hours

**Describe the solution you'd like**
Is there a way to somehow make the powerbank last longer? It seems like the leds draining power even when they're off.

**Comment by mariusmotea** [comment]
I believe the issue is the nodemcu2 that consume power even when is idle. I believe the leds consume very small amount of energy when are off and this can be verified with a multimeter by connecting just the leds to power. On thing you can do to improve the battery life is to change the 3.3v power supply for ESP-12E. On nodemcu2 there is a power regulator that is not efficient. You can use a step down power supply [like this](https://www.aliexpress.com/item/32765853201.html?spm=a2g0s.9042311.0.0.27424c4dQsYxLr) one with efficiency up to 92%

**Comment by AlexKusnezov** [comment]
@mariusmotea thanks, I'll try that out. The step down should connected between the power bank and the Ground and VIN of the nodemcu, right?

**Comment by mariusmotea** [comment]
@AlexKusnezov no, the step down output directly 3.3v and need to be connected to 3.3v pin of nodemcu. Also if you can connect the input of the step down directly to battery pins and bypass any other circuit from the power bank the efficiency will be higher.

**Comment by AlexKusnezov** [comment]
@mariusmotea ok thanks just to be clear you lean the 3.3v on the bottom right: https://pradeepsinghblog.files.wordpress.com/2016/04/nodemcu_pins.png?w=371&zoom=2

**Comment by mariusmotea** [comment]
Any pin marked with 3.3V you wish. Same label means same (duplicated) pin.
