### ISSUE TITLE
Save after every config action

### ISSUE THREAD

**Issue by alexyao2015** [diyhue/diyHue#212]
**Is your feature request related to a problem? Please describe.**
Add the save config function to run after every command that could require config changes. Ex. New room is created, new scene made, entertainment zone setup/reconfigured, light renamed.

Should be relatively easy, just need to find the all the places to add saving.
**Describe the solution you'd like**
A clear and concise description of what you want to happen. If you can provide an example solution then even better!

**Describe alternatives you've considered**

**Additional context**
Protects against restarts/etc before the config saves causing a loss of everything

**Comment by mariusmotea** [comment]
Bu i think something is not working properly because this is implemented already. In Hue API every object us created using http POST request. In the POST section of the webserver i also add the entry to save the config file. The config is also saved every hour and on service stop. Only when you change the state of a light and the process is killed the current light state will not be saved.

**Comment by alexyao2015** [comment]
I know that the config saving after every hour and the config saving after a light scan works. The backups also work. I haven't seen the config save any other time. Annoying when you change a room or entertainment zone before the 1 hour save.

**Comment by mariusmotea** [comment]
If you just edit there will be PUT HTTP request used for any change in bridge and this will not be saved automatically. When i implement this i consider lot of people will use Raspberry PI and i tried to void intensive disk writes because SD cards live will be impacted, so i added this just for objects creation and also every hour. GET and PUT http requests are allot in a bridge especially if you have motion sensors.
If this is really a problem for you is very easy to made a simple paste and add the saveconfig command to PUT requests exactly like i did for POST requests here https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/HueEmulator3.py#L1541

**Comment by alexyao2015** [comment]
Probably will have to do more testing but I think you are right that something is not working with the saveconfig after every post request.

**Comment by alexyao2015** [comment]
This needs to be fixed still
