### ISSUE TITLE
Handle docker stop gracefully

### ISSUE THREAD

**Issue by alexyao2015** [diyhue/diyHue#288]
Save config and quit program when docker stop is ran. 
Currently it force closes the program after a timeout.

Attempted a fix for this but couldn't quite get it working as I wanted it.

https://github.com/alexyao2015/diyHue/tree/debug-handleexit

**Comment by ryancasler** [comment]
To save the config, you only have to go to http://IP.of.DIYHUE/save  This will trigger DIYHue to save the config out to the location mapped out in Docker.  This is all that is done in the native SystemD file before the service is stopped.

**Comment by alexyao2015** [comment]
Yeah there's a way to detect when docker stop is called so all we need to do is figure out when its called save them exit. Right now it just forcibly closes it after the timeout period in docker

**Comment by mariusmotea** [comment]
It can be hard in python to detect OS kill signal, from what i remember i switch to systemd curl method because i did not like what i found when searching for a method.

**Comment by ryancasler** [comment]
@mariusmotea, instead of stopping the docker container directly, would the following method work? 

Let's say that the container is running in host network mode to make things easier.  You write the following bash script under the filename stophue.sh

```
#!/bin/bash
curl http://127.0.0.1/save
sleep 3
docker stop diyHue
```

You would then make it executable by `sudo chmod +x stophue.sh` and would then execute the scrip to stop your container rather than the docker command directly. 

All I know is that saving the config is definitely important before shutting down.  After some investigation I believe that not doing so was the reason for the "issues" that I reported a long time ago with my setup (#159, #136 , & #135 ).  I would be running in Debug mode and the only way out is the keyboard interrupt.  Well, doing that without manually saving the config file first is very bad and I wound up with a corrupted config.   Resulted in a lot of extra work but I learned a lot about how DIYHue works in the process.

**Comment by mariusmotea** [comment]
It will work but we need a method executed automatically when docker stop command take place.

**Comment by alexyao2015** [comment]
I have a way to detect it. I just can't get the script itself to stop properly. Look at the attempt that I made. I believe the os kill detection works fine

**Comment by svrooij** [comment]
Python code to check if docker wants to close application
```py
import signal
import sys

....

def signal_handler(sig, frame):
    print('Closing app')
    sys.exit(0)

signal.signal(signal.SIGINT, signal_handler)
print('Press Ctrl+C')
signal.pause()
```

**Comment by alexyao2015** [comment]
Thanks, I'll look into implementing this
