### ISSUE TITLE
Cannot search any light?

### ISSUE THREAD

**Issue by chrisdata** [diyhue/diyHue#33]
Today I delete all lights in Hue app and unable to search them, is it diyhue problem? I can connect to the bridge but unable to search any lights. They are all turned on and they are Yeelight 2nd hen RGB and yeelight plus strip

**Comment by mariusmotea** [comment]
You run container version or host version?

**Comment by chrisdata** [comment]
I run it on my Ubuntu virtual box on my MacOS Mojave as usual

**Comment by mdhaval** [comment]
1) When my bridge is running on Raspberry pi (physical board) , i am not able to search light 
2) but when i run the Bridge on Raspberry pi -( VM ) with virtual box, it runs well for static light operation but Hue Sync does not work in this mode. It detects light but there is no dynamic change in light as per screen or music

**Comment by mariusmotea** [comment]
@mdhaval can you please start the script manually and show the output during the light scanning? Check debug => wiki page for the exactly command. Please avoid using the wifi on Raspberry, there are know issues with the radio chip on Raspberry pi3 boards.

**Comment by mariusmotea** [comment]
Please increase the timeout during scanning in /opt/hue-emulator/HueEmulator3.py 

```
def scanHost(host, port):
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(0.01) # Very short timeout. If scanning fails this could be increased
```
put 0.1 seconds to be sure.

Don't forget to restart the service `sudo systemctl restart hue-emulator`

**Comment by mnoeth93** [comment]
for me this fixed the issue

**Comment by mdhaval** [comment]
Logs for Light not getting detected , 
Network is wired and Socket time out is set to --- 1 sec instead of .01..
Let me know if am i missing anything . Or anyone can point out the issue from log. 
The logs are for multiple attempt of light detection.
-----------------------------------------------------------------------------------
pi@raspberrypi:/opt/hue-emulator $ sudo ./HueEmulator3.py
192.168.43.166 - - [14/Jan/2019 23:41:35] "GET /api/config HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:41:48] "GET /api/config HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:41:48] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:41:49] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:41:50] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:41:51] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:41:52] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:41:53] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:41:54] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:41:55] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:41:56] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:41:57] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:41:59] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:00] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:01] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:02] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:03] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:04] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:05] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:06] "POST /api/ HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:42:06] "GET / HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:42:06] "GET /static/css/main.23de7225.css HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:42:06] "GET /config.js HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:42:06] "GET /static/js/main.7409e575.js HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:07] "POST /api/ HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:42:08] "GET /favicon-32x32.png HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:42:08] "GET /favicon-16x16.png HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:08] "POST /api/ HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:42:08] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:42:08] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:42:08] "GET /hue/linkbutton HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:42:09] code 404, message not found
192.168.43.88 - - [14/Jan/2019 23:42:09] "GET /favicon.ico HTTP/1.1" 404 -
192.168.43.166 - - [14/Jan/2019 23:42:09] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:10] "POST /api/ HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:42:10] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:11] "POST /api/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:11] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:11] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:21] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:31] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:37] "POST /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:37] "GET /api/a7161538be80d40b3de98dece6e91f90/lights/new HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:38] "POST /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:38] "GET /api/a7161538be80d40b3de98dece6e91f90/lights/new HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:39] "POST /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:39] "GET /api/a7161538be80d40b3de98dece6e91f90/lights/new HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:39] "POST /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:39] "GET /api/a7161538be80d40b3de98dece6e91f90/lights/new HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:41] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:42:51] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:43:01] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:43:03] "PUT /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:43:05] "POST /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:43:05] "GET /api/a7161538be80d40b3de98dece6e91f90/lights/new HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:43:11] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:43:21] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.43.166 - - [14/Jan/2019 23:43:31] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:44:05] "GET /api/temporary HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:44:05] "POST /api/ HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:44:06] "POST /api/ HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:44:07] "POST /api/ HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:44:08] "POST /api/ HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:44:09] "POST /api/ HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:44:10] "POST /api/ HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:44:11] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:44:11] "POST /api/ HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:44:11] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:44:15] "PUT /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:44:15] "POST /api/a7161538be80d40b3de98dece6e91f90/lights/ HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:44:23] "GET /api/a7161538be80d40b3de98dece6e91f90/lights/new HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:44:38] "PUT /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:44:38] "POST /api/a7161538be80d40b3de98dece6e91f90/lights/ HTTP/1.1" 200 -
192.168.43.88 - - [14/Jan/2019 23:44:45] "GET /api/a7161538be80d40b3de98dece6e91f90/lights/new HTTP/1.1" 200 -
