### ISSUE TITLE
No New Hue Bridge Found

### ISSUE THREAD

**Issue by debojitk** [diyhue/diyHue#349]
**Describe the bug**
I took the docker image diyhue:core/latest released 9 days ago. Now as per the documentation I go to Link device section and enter the username and password. In the Hue App when I search for new bridge or go to help section for entering the IP, the app shows "No New Hue Bridge Found".
I checked with wireshark and found that the following url is hit
`http://<ip>/api/nouser/config` and the response sent is:
```
{
  "name": "Philips hue",
  "datastoreversion": 70,
  "swversion": "1935144020",
  "apiversion": "1.35.0",
  "mac": "2C:4D:54:EA:28:32",
  "bridgeid": "2C4D54FFFEEA2832",
  "factorynew": false,
  "replacesbridgeid": null,
  "modelid": "BSB002",
  "starterkitid": ""
}
```

**To Reproduce**
1. Start docker with bridge mode on windows 
2. Open Hue app
3. Go to Help and enter host ip
4. See error - No New Hue Bridge Found

**Expected behavior**
The app should be able find the diyhue instance

[config.TXT](https://github.com/diyhue/diyHue/files/4306574/config.TXT)

**Comment by mariusmotea** [comment]
I think in the new Hue version of the Hue app, if internet connection is detected then is used cloud based detection witch works only with real Hue bridges. Instead to cut the internet connection in order to revert to local network SSDP discovery, you can click Help button in the app and enter the ip of the emulator (192.168.0.104 based uploaded config). If you reinstalled the emulator (and generate new certificate) you need to wipe or reinstall the hue app.
