### ISSUE TITLE
Domoticz : light configuration for color change with Hue Essentials

### ISSUE THREAD

**Issue by Jognu** [diyhue/diyHue#385]
Hi,
I try to setup a light from Domoticz which support light color change, I saw the commit from @jespertheend which add this.

The example on the documentation is about a simple on/off switch.

I used the Extended color light type and copy the configuration from a Philipps hue lamp. I put the colormode to "ct".
From the diyhue interface : no problem, everything work fine.

But when I change the color from Hue Essentials, it switch the colormode to "hs", which is not working for Domoticz.

I don't know if the problem is about my light configuration in config.json (it would be great to have an example for a color light in the documentation), or if it's a problem with Hue Essentials.

Any idea ?

Thanks !

**Comment by mariusmotea** [comment]
In hue api are accepted CIE and HUE values for colors. I think in docoticz only CIE was implemented. The conversion from HUE (hs) to CIE (xy) can be done with build in functions because we can convert hs to rgb and rgb to xy

**Comment by jespertheend** [comment]
It's been a while since I implemented this and to be honest I don't remember much about it anymore. I'm no longer using diyHue for my lights so I don't have a working setup anymore.
But perhaps if you show  me your current config I might remember a thing or two and I might be able to help.

If you want to figure out if Hue Essentials might be the issue, you can try and change the lights from the diyHue web panel. If that works, it might be related to diyHue. Otherwise it's probably Hue Essentials.

**Comment by Jognu** [comment]
Indeed the problem is that domoticz does not support HUE (hs), and Hue Essentials use this (if you use the "color selector thing").
Like suggested bye @mariusmotea, I used the build in functions to convert to HUE to rgb and to xy, like it done for the ikea_tradfri protocol.
I'll try to propose a PR for this.
