### ISSUE TITLE
Lights in Entertament mode are laggy while Milight bulbs are added to an area 

### ISSUE THREAD

**Issue by 0x7878** [diyhue/diyHue#487]
**Describe the bug**
I bought some E14 Milights bulbs and built a milight hub as documented. Everything works fine except Entertainment. The response of the lights seems to be delayed. For instance, when I maximize and minimize a white window on a black background in video mode, lights won't react. Sometimes the color change after a while and sometimes not. Also, the transition is very laggy. 
Whenever you remove milights bulbs from your entertainment area, everything works fine then.

**To Reproduce**
1. Go to Settings in your hue app
2. add a milight light to an entertainment area
3. start Hue sync on a PC
4. See the problem

**Expected behavior**
I would expect that event if my milight bulb isn't reachable, the rest of my setup would work as before.

**Additional context**
It's strange. Is there any sync behavior to pass the data simulants to all lights? I can't explain why the whole setup starts to lag. Any ideas or help?

**Comment by mariusmotea** [comment]
You cannot obtain realtime performance with milight hub because of device low performance. From what you describe it seams the milight hub is overloaded.  In [develop branch](https://github.com/diyhue/diyHue/blob/develop/BridgeEmulator/functions/entertainment.py) i refactor the entertainment funtion to send just the frames where the brightness of the color are below a treshhold but this was not made yet public.

**Comment by 0x7878** [comment]
First of all, thank you for the fast response. I'd checked your improvements in that file and copy the code plus the Globals.py as it's required now. 

In my config file, there is only one milight bulb where I tested the above behavior.  Therefore, I'm not sure if the hub is overloaded with only one bulb connected.


Here is the specific device: 

```

"9": {
            "device_id": "0x1",
            "group": 1,
            "ip": "192.168.1.224",
            "mode": "rgb_cct",
            "protocol": "milight"
        }

```

I'm not a Python developer but I guess you pass the Protocol as the second parameter to the function/Service:

```Python
Thread(target=entertainmentService, args=[bridge_config["lights"], bridge_config["lights_address"], bridge_config["groups"], HOST_IP]).start()
```

Later you check which Protocol is affected: 

```Python
[...]
if data[14] == 0: #rgb colorspace
    i = 16
    while i < len(data):
        if data[i] == 0: #Type of device 0x00 = Light
            [...]
                proto = addresses[str(lightId)]["protocol"]
                [...]
                if proto in ["native", "native_multi", "native_single"]:
                    [...]
                elif proto == "esphome":
                    [...]
                elif proto == "mqtt":
                   operation = skipSimilarFrames(lightId, lights[str(lightId)]["state"]["xy"], lights[str(lightId)]["state"]["bri"])
                   [...]
                elif proto == "yeelight":
                    operation = skipSimilarFrames(lightId, lights[str(lightId)]["state"]["xy"], lights[str(lightId)]["state"]["bri"])
                    [...]
                else:
                    if fremeID % 4 == 0: # can use 2, 4, 6, 8, 12 => increase in case the destination device is overloaded
                        [...]
                        operation = skipSimilarFrames(lightId, lights[str(lightId)]["state"]["xy"], lights[str(lightId)]["state"]["bri"])
                          [...]
elif data[14] == 1: #cie colorspace
[...]
``` 

I guess the else part sends then the commands here. Unfortunately, after I copied the new code the Milight bulbs cause an error. (not in net_accept()) 

See the output: 

```
  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Loading the server cert. and key... ok
  . Bind on udp://*:2100/ ... ok
  . Setting up the SSL/TLS structure... ok
  . Waiting for a remote connection ...
{"ok"}
 ok
  . Performing the SSL/TLS handshake... hello verification requested
  . Waiting for a remote connection ... ok
  . Performing the SSL/TLS handshake... ok
    [ Protocol is DTLSv1.2 ]
    [ Ciphersuite is TLS-PSK-WITH-AES-128-GCM-SHA256 ]
    [ Record expansion is 37 ]
    [ Maximum fragment length is 16384 ]
  . Verifying peer X.509 certificate... ok
 mbedtls_ssl_read returned -0x45
 interrupted by SIGTERM (not in net_accept())
  . Cleaning up... done.
```
without the bulb inside the area, Entertainment works as expected. 

```
 . Loading the CA root certificate ... ok (0 skipped)
  . Loading the server cert. and key... ok
  . Bind on udp://*:2100/ ... ok
  . Setting up the SSL/TLS structure... ok
  . Waiting for a remote connection ...{"ok"}
192.168.1.24 - - [30/Oct/2020 12:14:44] "GET /api/19a52a92ffcf11ea8427b827ebcdae3a/lights HTTP/1.1" 200 -
192.168.1.24 - - [30/Oct/2020 12:14:44] "GET /api/19a52a92ffcf11ea8427b827ebcdae3a/groups HTTP/1.1" 200 -
 ok
  . Performing the SSL/TLS handshake... hello verification requested
  . Waiting for a remote connection ... ok
  . Performing the SSL/TLS handshake... ok
    [ Protocol is DTLSv1.2 ]
    [ Ciphersuite is TLS-PSK-WITH-AES-128-GCM-SHA256 ]
    [ Record expansion is 37 ]
    [ Maximum fragment length is 16384 ]
  . Verifying peer X.509 certificate... ok
```

I really love this project. It would be amazing to have the bulbs working. :-)

**Comment by 0x7878** [comment]
Well, I've got it running now but the issue persists. I've made a video to show whats the problem is. You'll see my esp8266 RGB strip but basically, every light starts to lag if the milight bulb is added to the entertainment area. 

Here's how it looks like without the milight bulb: 
<https://www.youtube.com/watch?v=CHnWxH0khDI>

And here when the bulb is connected: 
<https://www.youtube.com/watch?v=wI5N72hAem4>

**Comment by alexyao2015** [comment]
Entertainment mode is simply difficult to get working unless there is a proper api that allows for fast changes. Any "fix" will be a workaround and not optimal. For best operation using entertainment mode, suggest using something like esphome.

**Comment by mariusmotea** [comment]
Copy and paste of the new entertainment function will nor work because of globals.py nor implemented. You may try entire code of that branch or try to implement only the function that manage the frames and sens only the ones that differ.

**Comment by 0x7878** [comment]
Thank you for your help. I've solved the issue so far by changing the protocol to UDP via Mi_box (only change there was to reduce tries argument to 2). The requests are sent via:

```Python
Thread(target=sendLightRequest, args=(str(lightId), {"bri": lights[str(lightId)]["state"]["bri"], "transitiontime": 3}, lights, addresses, None, host_ip,)).start()
```

Furthermore, I skip some frames so I don't overload the milight hub

```Python
 if fremeID % 8 == 0: # can use 2, 4, 6, 8, 12 => increase in case the destination device is overloaded
``` 

every 8 frames seem to be good enough here. Also, I speed up the ESP8266 by 160MHz and optimize the radio parameter. The only issue is now a small delay (~100-200ms) between "native" lights and "milight" lights. I guess it is because of the circumstances. Hue App -> DIYHue -> MilightHub --> Milight Light. 

At this point, I give up on experimenting and use the "milight" lights as there are, without "entertainment-mode".

**Comment by alexyao2015** [comment]
The best way to would be to save the last sent frame, compare the new frame to the last frame, and only send the packet if it passes a difference threshold. Though as originally mentioned, any methods used are going to be hacks or workarounds. Nothing we can really do about it.

**Comment by mariusmotea** [comment]
If somebody can convert the code and run the rf2.4ghz module directly from raspberry pi GPIO's then is possible to obtain identical response time like the original hue bulbs. Or a way to send UDP frames to milight hub instead of http json's that consume lot of resources.

**Comment by 0x7878** [comment]
Hey Guys,

thanks again for your participation. I picked up your tips and started a pull request #491 

> If somebody can convert the code and run the rf2.4ghz module directly from raspberry pi GPIO's then is possible to obtain identical response time like the original hue bulbs. Or a way to send UDP frames to milight hub instead of http json's that consume lot of resources.

I tested the rf2.4ghz module beforehand to see that it was fast enough in the end. I made also a project based on diyHue to test the speed and fluency. 
You can find this project here [diyHue_MiLight_tests](https://github.com/0x7878/diyHue_MiLight_tests). I use only UDP to communicate. 

I found some issues which slow down the overall processing as you can see in the pull requests. It's working much better now. However, from time to time you'll see some latency issues but not just the Milight bulbs also native lights need some time to come back on track. Maybe my Wifi Connection isn't stable enough. I don't know.  
The Milights bulbs are not so fast as the Native Lights in my solution but I think it is because of the RF technology. 
Anyway, I'm pretty happy with it so far.

**Comment by Shaggy013** [comment]
it still through network ;)
perhaps this aproach is more the way 
https://github.com/drewligman/arduino-milight-controller
 pair with receiver (the bulb) and send commands to change the state of light .
this took just the code from the milighthub to work with milight on a arduino. 
think it is also not to hard to run it without a arduino the radio files are not that diffrent from the rpi version of it .
https://github.com/Sebbb/openmilight_pi

**Comment by Shaggy013** [comment]
> 
> 
> If somebody can convert the code and run the rf2.4ghz module directly from raspberry pi GPIO's then is possible to obtain identical response time like the original hue bulbs. Or a way to send UDP frames to milight hub instead of http json's that consume lot of resources.

I got it running on a orange pi and in python3 and with spi :) think even a usb serial is possible for the non solder fanatics just another nrf24l01 version .
we talked a little in the lights git about it ;)



> 
> 
> Hey Guys,
> 
> thanks again for your participation. I picked up your tips and started a pull request #491

> 
> I tested the rf2.4ghz module beforehand to see that it was fast enough in the end. I made also a project based on diyHue to test the speed and fluency.
> You can find this project here [diyHue_MiLight_tests](https://github.com/0x7878/diyHue_MiLight_tests). I use only UDP to communicate.
> 
> I found some issues which slow down the overall processing as you can see in the pull requests. It's working much better now. However, from time to time you'll see some latency issues but not just the Milight bulbs also native lights need some time to come back on track. Maybe my Wifi Connection isn't stable enough. I don't know.
> The Milights bulbs are not so fast as the Native Lights in my solution but I think it is because of the RF technology.
> Anyway, I'm pretty happy with it so far.

nrf24l01 is faster as pl1167 or zigbee ;)
https://tmrh20.blogspot.com/2019/05/comparative-performance-analysis.html

for milighthub on rpi and spi and also python3 (what a wishes :) )

https://github.com/dmkent/pymilight

it uses the same source for the radio as the milighthub ;) and sure can be improved but python dont knows me :)
 
add  #cython: language_level=3 to the pyx files otherwise it warns about that it use something with 2 
and configure your spi port the right way in milight_control.py
rf = RF24.RF24(RF24.RPI_V2_GPIO_P1_15, RF24.BCM2835_SPI_CS0, RF24.BCM2835_SPI_SPEED_8MHZ)
for example got a orange pi with a nrf24l01 module on spi1 and cs pin on gpio 2 with spidev  then the line is 
rf = RF24.RF24(2,10)
for more info how to set spi bus 
http://tmrh20.github.io/RF24/RPi.html

it has a mqttclient so you can test that the engine works , would only need a diyhue glue script instead of he mqtt glue 
and a mqtt command look for example like this 
("rgb_cct", 0x1, 1, {"status": "on"}
("rgb_cct", 0x1, 1, {"status": "off }
and the config.json is something like this 
{"mqtt_host":"ip","mqtt_port":1883,"mqtt_username":"username","mqtt_password":"password","mqtt_topic_pattern":"milight/:device_id/:device_type/:group_id","mqtt_update_topic_pattern":"milight/updates/:device_id/:device_type:group_id","mqtt_state_topic_pattern":"milight/states/:device_id/:device_type:group_id",,"mqtt_client_status_topic":"milight/client_status","simple_mqtt_client_status":true}

and if you got a remote you see that it also catch the radio packets of that 

and for serial milight 
https://github.com/khmann/milightx-firmware

only for that i not have a example how that works yet

**Comment by 0x7878** [comment]
@Shaggy013  Thank you for your effort! I'll try those things out to see how it works. 

If direct communication over MQTT on a second device (Raspberry Pi or PC via COM ) is fast enough I'd like to implement a new protocol for this purpose. I'll quite busy right now and I hope I'll find some time.

**Comment by Shaggy013** [comment]
> 
> 
> @Shaggy013 Thank you for your effort! I'll try those things out to see how it works.
> 
> If direct communication over MQTT on a second device (Raspberry Pi or PC via COM ) is fast enough I'd like to implement a new protocol for this purpose. I'll quite busy right now and I hope I'll find some time.

you could also use the same rpi , it is just how you call the milightclient python script for exmple from pymilight.milight_control import MiLightController instead calling the sendLightRequest 

and do a process_command or send_radio_command instead of a sendLightRequest 

in your testscript 

no http,mqtt,udp just python to spi or serial .  the main.py only puts a mqtt call in a inbound que and milightclient reads that inbound que and calls process_command

and while it would be nice to have it running in python there are lots of examples in c already old and new , the milighthub is pretty broken with all it extras build in .and most of it is not needed diyhue is the remote 

only what i dont read anywhere is how fast are the controllers aka receivers almost every milight sender has programmed a delay into it to avoid troubles for missng commands .

and cannot find any firmware for the controllers only found this 
https://www.vincentgijsen.nl/post/let-there-be-source-milight-alternative-firmware/
https://github.com/VincentGijsen/milight-alternative-firmware

the question is how fast is the receiver instead how fast can i send a command because milight is dumb it only receives ?
