### ISSUE TITLE
Unable to connect to bridge

### ISSUE THREAD

**Issue by HudsonCory** [diyhue/diyHue#5]
When attempting to connect to bridge emulator, connection fails and app reports unable to connect.
I have updated to newest emulator and problem has not been resolved. This issue has only recently started. I have not had this issue in the past. em running on ubuntu vm.

**Comment by mariusmotea** [comment]
Hi,

We had a bug in certificate generation script that put short validity on this certificate. Very likely this is the issue. You can check with curl command specified in wiki that display also the certificate validity. To fix this you need to delete the file `/opt/hue-emulator/cert.pem` and to execute again the installation script. You will also need to wipe the hue app data if you use Android or reinstall it if you use iOS because the old certificate is cached by the app.

**Comment by HudsonCory** [comment]
Thanks for quick response. I will attempt this today and get back to you.
Cheers

**Comment by HudsonCory** [comment]
which curl command in wiki do you mean?

**Comment by HudsonCory** [comment]
nvm. problem resolved. This issue can be closed. thanks for your help. 
Cheers!
