### ISSUE TITLE
Connect Ikea light with Hue Bridge

### ISSUE THREAD

**Issue by dwainscheeren** [diyhue/diyHue#52]
I now have 2 Ikea lamps connected to my Hue Bridge and they are working as 'Hue Lights'. But they are not working in the entertainment rooms.

I found this project and I thought maybe with this I can add other lights besides Hue to use as lights in a entertainment room ( I don't want to buy expensive Hue lights for in garage but want to use sync for parties in the garage).

As I read it's possible with lights connected to this emulator to use in the entertaiment room. Is it possible to connect Ikea lights to my Hue bridge which is connect to this Hue bridge emulator and use that Ikea lights in a entertainment room or do I need to use the Raspbee module or the Ikea bridge to connect the Ikea lights to and then add them in the hue entertainment room?

**Comment by mariusmotea** [comment]
You may use them but i'm not sure if is straightforward and for sure you will have delay between 0.5 and 1 second. If you want something cheep with instant reply and with more futures buy ws2812 led strips and connect them to one esp8266 device flased with the firmware we provide.

**Comment by dwainscheeren** [comment]
It's indeed maybe better to make a ledstrip with a esp8266 connect it to Hue emulator. That works seemly with entertainment rooms?

What about this method? https://char.gd/blog/2018/building-better-cheaper-philips-hue-led-strips using a https://sale.aliexpress.com/__pc/affi-item.htm?ae_affi_item_id=32858603964 and a ledstrip and connect that to the Hue bridge as a Hue ledstrip. In that blog it says that is not working with entertainment rooms but with this emulator is it possible to get that working or?

Thanks.

**Comment by mariusmotea** [comment]
In our esp8266 firmware is integrated a dedicated udp service that is able to handle frames at fast speed (entertainment send about 25/second) and most of smart lights don't support this rate (ex: Yeelight has max 144/min). The reason why with original hue bridge work only original philips lights is similar, they integrate something proprietary that is not in zigbee standard. One of the big reason why ws8212 strips are recommended for entertainment is because you can split them in multiple virtual lights, and this is currently not possible to do even with original Philips Hue Strip.

**Comment by dwainscheeren** [comment]
I bought a D1 mini and got the ESP8266 working on it. I created a ledstrip and I added the light in the Hue app. Only when I want to add them to an entertainment room. The app says the lamps needs a update. How can we fix this?

**Comment by dwainscheeren** [comment]
Thanks. I followed your advice with the esp8266 and a ws2812 ledstrip its working now. https://www.youtube.com/watch?v=CmOaaY-JsgM

**Comment by mariusmotea** [comment]
Nice video.
