### ISSUE TITLE
Run on the philips hue bridge itself

### ISSUE THREAD

**Issue by XtremeCoder007** [diyhue/diyHue#7]
Hi,

I was just wondering since this is python and the hue bridge runs openwrt, could you maybe develop a package that we can install via cli on the bridge ?

only 1 time-access on the pcb is needed to access the openwrt on the bridge.

And since this bridge (2.0) also has wifi HW but not activated we can use this to connect directly to devices.

Just a tought.

kind regards,
XtremeCoder007

**Comment by mariusmotea** [comment]
Hi,

I don't recommend users to root their hue bridges because in some cases this can brick the devices so is a very big responsibility for me. Second issue is that i don't have any documentation of the integrated ZigBee module so i don't know how to use it. The integrated wifi is disable because it may impact zigbee communication, until they will not find a way to avoid transmission of both devices in the same time they keep this disabled.

**Comment by XtremeCoder007** [comment]
> Second issue is that i don't have any documentation of the integrated ZigBee module so i don't know how to use it. 

I do understand your concerns, i'll just try it myself and see how it goes.

Here's the datasheet of the zigbee module being used:
[http://www.skyworksinc.com/uploads/documents/SE2438T_202414I.pdf](url)

Kind regards,

XtremeCoder007

**Comment by mariusmotea** [comment]
Yes, but you need to write code to have this chip as ZigBee Coordinator and then read the ZigBee parameters of all lights. If you made any progress i can support you with integration.

**Comment by cheesemarathon** [comment]
I'm as it's sort of solved for now @XtremeCoder007 Feel free to update us on your progress in this issue or join us on Slack, thanks!
