### ISSUE TITLE
Yeelight quota exceeded using Ambilight + Hue

### ISSUE THREAD

**Issue by joaquinvacas** [diyhue/diyHue#782]
**Describe the bug**

Hi there! 👋

Using diyHue with a Yeelight color bulb and a Philips TV (non Android TV)

Everything is fine, works good, easy installation and so on.

The issue here is that works fine for at least half minute, because it shows the error "client quota exceeded" and AFAIK it's just an issue with the yeelight library (happened in python-yeelight, check https://gitlab.com/stavros/python-yeelight/-/issues/73 ) that's used for talking with the bulb.

Because the bulb can handle all of this when using the music mode and works fine with other projects using python-yeelight.

Using last version.

Tried beta but didn't change a thing.

**Steps to Reproduce**

**Expected behavior**

Yeelight should keep up with all commands without exceeding any quota.

**Logs**

The error was:

2022-02-14 15:50:45,526 - HueObjects - WARNING - piesalon light error, details: {'code': -1, 'message': 'client quota exceeded'}

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): x86
 - Docker image version (Ex: latest, arm-05f043b, 128): latest
 - OS (Ex: Windows 10, Ubuntu Buster): Arch/Docker
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): PC

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
I reopen the previews issue and reply to you there.

**Comment by joaquinvacas** [comment]
Actually the problem it's that the Yeelight stops while the "quota is exceeded" and it starts working again over a minute. This works in a loop like 30s-45s working, 1min of sleep, 30s-45s working, sleep, working, sleep... And so on.

**Comment by mariusmotea** [comment]
Unfortunately at code level is very hard to found an workaround. Not sure if you want to use a custom release that add an additional sleep command so the TV probably will not send a new request until it receive a response. If the delay is added to the response the quota will not be exceeded but the "refresh rate" of the light will also be affected since the number of requests from the tv will be lowered.

**Comment by joaquinvacas** [comment]
Doesn't sound like a good experience at all :laughing: 

Sorry to ask again, but if I make a LED RGB strip using ESP8266 it will work nice with this kind of TVs?

**Comment by mariusmotea** [comment]
If you make a WS2812 stip with esp8266 it will work in realtime, but your TV will not be faster, will not start to use entertainment protocol since it don't had that implemented. The difference will be that it will not stop (because of quota, etc), with Hue Essentials and Hue Sync you can stream in realtime and you can split the same strip into multiple lights to show different color (ex: left side of the TV will made left strip a color and so on)
