### ISSUE TITLE
OpenWRT install script updated.

### ISSUE THREAD

**Issue by FerrumMaster** [diyhue/diyHue#852]
I am trying to install it on openwrt.

The install script totally doesn't match the current git. Zips archive not present, web-ui to flask migration.

Please remove it if you are not willing to maintain it anymore.

**Comment by juanesf** [comment]
The problem should be fixed, the instructions in the documentation point to the script "easy_openwrt.sh" so you should use: 
`wget --no-check-certificate https://raw.githubusercontent.com/diyhue/diyHue/master/BridgeEmulator/install_openwrt.sh && sh install_openwrt.sh`

**Comment by FerrumMaster** [comment]
Thanks Juan.

I managed to get it working.

My few suggestions.

It needs Python3 >= 3.8 otherwise pyyaml breaks on 3.7. My Router had that version. Okay. did a snapshot of the latest stable 22.0.3.0 from scratch, not the factory build.

I did the script manually step by step, as running it at once failed for me. The requirements.txt file should be installed manually according to your device, as it usually failed first, first of all some parts are in my opkg repo without any need to compile, then install the missing ones via pip command. Using python3 -m pip install -r caused me error(a simple error code -1 without any log or additional info) also using plain pip install xxx, worked fine. Could be platform specific.

The last step via nano edit(nano /etc/config/uhttpd). It should be done like that. More elegant.

`uci -q delete uhttpd.main.listen_http
uci add_list uhttpd.main.listen_http="0.0.0.0:8080"
uci add_list uhttpd.main.listen_http="[::]:8080"
uci -q delete uhttpd.main.listen_https
uci add_list uhttpd.main.listen_https="0.0.0.0:8443"
uci add_list uhttpd.main.listen_https="[::]:8443"
uci commit uhttpd
/etc/init.d/uhttpd restart`

Also there is no /etc/lighttpd/lighttpd.conf file in latest OpenWRT builds to edit. Can be skipped.

Also I had to toggle many times the service enable, till it really was enabled after reboot. That's esoteric, I didn't find a clue why. I suspected nohup param before python3 in the service script, but I guess really not. 

Next thing is minimum HW requirements. This install script cannot be installed on a 128MB RAM router. It will fail at installing bleak dependency. Enabling SWAP the most easy fix, but it is usually disabled. In the end with some HW mods it runs on a spartan gl-inet microuter-n300.

So the front page guide needs fixing also for any newcomers. Also some signs with dragons ahead.

**Comment by juanesf** [comment]
Hi @FerrumMaster.
Thanks for the suggestions, I'll check it out...

- I will investigate the problem about the python version
- The failure of the requirements did not happen to me in my tests (Khadas Vim 1), I am going to try in my mini router that has less resources (GL-MT300A).
- When I checked the precompiled packages in the official repositories I am going to change the script so that it installs fewer pip packages (increases the installation speed of the script).
- Thank you very much for the suggestion of using UCI, I will try and try to implement it.
- In my first installation tests on the GL-MT300A router that comes with OpenWrt compiled by Gl-iNet it has a double web interface and it was necessary to modify both files, perhaps I should suggest omitting it if it does not exist.
- The issue about the startup script I will investigate on different devices.
- On the subject of the minimum requirements, it is clear that it must have enough space and memory (by default I add swap and overlayroot). I'm not sure what the minimum resources should be (suggestions welcome, thanks).

If you want to continue helping and comment, I would be very grateful for your help. You could also enter the Slack group to keep in touch in case you need it.
